package me.xx2bab.bro.compiler.util

import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.TypeSpec
import me.xx2bab.bro.annotations.BroModule
import me.xx2bab.bro.common.Constants
import javax.annotation.processing.Filer
import javax.lang.model.element.Modifier

/**
 *
 */
object DummyClassCreator {

    const val packageName = Constants.GEN_PACKAGE_NAME
    const val className = "DummyClassForTriggeringAnnoProcess"
    const val canonicalName = "$packageName.$className"

    fun create(filer: Filer) {
        val clazz = TypeSpec.classBuilder(className)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(BroModule::class.java)
                .build()

        val file = JavaFile.builder(packageName, clazz)
                .indent("    ") // with 4 spaces
                .addFileComment("Generated by Bro.")
                .build()

        file.writeTo(filer)
    }

}