package me.xx2bab.bro.compiler.collector;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

import me.xx2bab.bro.common.anno.AnnotatedElement;
import me.xx2bab.bro.common.IBroGenerator;

/**
 * To collect all meta data json files that generated by SingleModuleCollector,
 * and expose them to generators.
 *
 * @see SingleModuleCollector
 * @see IBroGenerator
 */
public class MultiModuleCollector implements IAnnotationMetaDataCollector<List<AnnotatedElement>> {

    private String appPackageName;
    private File appAptGenDirectory;
    private File moduleBroBuildDirectory;
    private List<IBroGenerator<List<AnnotatedElement>>> generators;

    private List<AnnotatedElement> entireTable = new ArrayList<>();

    public MultiModuleCollector(String appPackageName,
                                String appAptGenPath,
                                String moduleBroBuildPath,
                                List<IBroGenerator<List<AnnotatedElement>>> generators) {
        this.appPackageName = appPackageName;
        this.appAptGenDirectory = new File(appAptGenPath);
        this.moduleBroBuildDirectory = new File(moduleBroBuildPath);
        this.generators = generators;
    }

    @Override
    public List<AnnotatedElement> getMetaData() {
        return entireTable;
    }

    @Override
    public void addMetaRecord(List<AnnotatedElement> singleModuleMetaData) {
        if (singleModuleMetaData != null) {
            entireTable.addAll(singleModuleMetaData);
        }
    }

    @Override
    public void generate() {
        if (generators == null) {
            return;
        }
        generators.forEach(new Consumer<IBroGenerator<List<AnnotatedElement>>>() {
            @Override
            public void accept(IBroGenerator<List<AnnotatedElement>> broGenerator) {
                broGenerator.onGenerate(entireTable,
                        appPackageName,
                        appAptGenDirectory,
                        moduleBroBuildDirectory);
            }
        });
    }


}
