package me.xx2bab.bro.core

import android.content.Context
import me.xx2bab.bro.core.activity.IBroActivityFinder
import me.xx2bab.bro.core.base.IBroInterceptor
import me.xx2bab.bro.core.base.IBroMonitor
import me.xx2bab.bro.core.util.BroRudder
import java.lang.ref.WeakReference

data class BroContext(val interceptor: IBroInterceptor,
                      val monitor: IBroMonitor,
                      val broRudder: BroRudder,
                      val context: WeakReference<Context>,
                      val fallbackActivityCls: Class<*>,
                      val activityFinders: List<IBroActivityFinder>,
                      val activityTransition: IntArray,
                      val apiCacheEnabled: Boolean) {

    // Generated by Android Studio, do not modify manually
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as BroContext

        if (interceptor != other.interceptor) return false
        if (monitor != other.monitor) return false
        if (broRudder != other.broRudder) return false
        if (context != other.context) return false
        if (fallbackActivityCls != other.fallbackActivityCls) return false
        if (activityFinders != other.activityFinders) return false
        if (!activityTransition.contentEquals(other.activityTransition)) return false
        if (apiCacheEnabled != other.apiCacheEnabled) return false

        return true
    }

    // Generated by Android Studio, do not modify manually
    override fun hashCode(): Int {
        var result = interceptor.hashCode()
        result = 31 * result + monitor.hashCode()
        result = 31 * result + broRudder.hashCode()
        result = 31 * result + context.hashCode()
        result = 31 * result + fallbackActivityCls.hashCode()
        result = 31 * result + activityFinders.hashCode()
        result = 31 * result + activityTransition.contentHashCode()
        result = 31 * result + apiCacheEnabled.hashCode()
        return result
    }

}